model:
  type: random_forest
  params:
    n_estimators: 500
    random_state: 0
    class_weight: 'balanced'
    n_jobs: 4

paths:
  model: models/

seed: 42

features:
  - neighbourhood
  - room_type
  - accommodates
  - bathrooms
  - bedrooms

target: category


train_config:
  test_size: 0.15
  random_state: 1
  