version: "3.7"

services:

 airbnb-price-prediction:
  image: airbnb-price-prediction
  volumes:
   - ../:/app/
  stdin_open: true
  tty: true
  ports:
   - "8000:8000"
  command: uvicorn api:app --host 0.0.0.0 --port 8000