name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Cambiado a write para permitir el deploy de docs
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        echo "API_TOKEN=$API_TOKEN" >> .env
        echo "Archivo .env creado con API_TOKEN configurado"
        cat .env
    - name: Run flake8
      run: flake8 .
    - name: Launch API with Docker
      run: |
        chmod +x ./launch.sh
        ./launch.sh --docker
        echo "API lanzada con docker compose"
    - name: Run tests with coverage
      run: |
        coverage run run_tests.py
        coverage report
        coverage xml
    - name: Remove .env file
      run: rm .env
