name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "API_TOKEN=${{ secrets.API_TOKEN }}"
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" > .env
    - name: Run flake8
      run: flake8 .
    - name: Lanzar API en segundo plano
      run: |
        chmod +x ./launch_api.sh
        nohup ./launch_api.sh > api.log 2>&1 &
        echo "API lanzada en segundo plano"
        sleep 10  # Esperar a que la API se inicie completamente
    - name: Run tests with coverage
      run: |
        coverage run run_tests.py
        coverage report
        coverage xml
    - name: Remove .env file
      run: rm .env
