name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" > .env
    - name: Run flake8
      run: flake8 .
    - name: launch api
      run: chmod +x ./launch_api.sh && ./launch_api.sh
    - name: Run tests with coverage
      run: |
        cd lab
        coverage run -m unittest discover -v tests
        coverage report
        coverage xml
    - name: Remove .env file
      run: rm .env
