name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      shell: bash
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        echo "API_TOKEN=$API_TOKEN" > .env
        echo "Archivo .env creado con API_TOKEN configurado"
    - name: Verificar .env file
      shell: bash
      run: |
        if grep -q "API_TOKEN=" .env; then
          echo "El valor de API_TOKEN es: $(grep API_TOKEN .env | cut -d '=' -f2)"
        else
          echo "Error: API_TOKEN no está configurado en .env"
          exit 1
        fi
        ls -l .env
    - name: Run flake8
      run: flake8 .
    - name: Lanzar API en segundo plano
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        chmod +x ./launch_api.sh
        nohup ./launch_api.sh > api.log 2>&1 &
        echo "API lanzada en segundo plano"
        sleep 10  # Esperar a que la API se inicie completamente
    - name: Run tests with coverage
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
      run: |
        coverage run run_tests.py
        coverage report
        coverage xml
    - name: Remove .env file
      run: rm .env
